# cspell:disable

[project]
name = "logic1"
dynamic = ["version"] # See https://setuptools-scm.readthedocs.io/en/v8.1.0/usage/
description = "Interpreted first-order logic in Python"
authors = [
  {name = "Nicolas Faroß", email = "faross@chalmers.se"},
  {name = "Thomas Sturm", email = "tsturm@me.com"}
]
license = "GPL-2.0-or-later"
license-files = ["./LICENSE"]
maintainers = [
  {name = "Nicolas Faroß", email = "faross@chalmers.se"},
  {name = "Lorenz Leutgeb", email = "lorenz@mpi-inf.mpg.de"},
  {name = "Thomas Sturm", email = "tsturm@me.com"}
]
readme = "README.md"
dependencies = [
  "gmpy2",
  "more-itertools",
  "networkx",
  "pyeda",
  "python-flint",
  "sagelite",
  "typing-extensions",
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3",
  "Typing :: Typed"
]

[project.optional-dependencies]
dev = [
  "build",
  "coverage",
  "Cython>=3.1.0",
  "graphviz",
  "jupyter",
  "line-profiler",
  "mypy",
  "pytest",
  "pytest-cython",
  "pytest-xdist",
  "setuptools",
  "setuptools-scm",
  "snakeviz",
  "sphinx",
  "sphinx-book-theme",
  "types-networkx",
  "viztracer",
]

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "Cython>=3.1.0", "gmpy2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["logic1*"]

[tool.setuptools_scm]
