name: docs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04
    env:
      CFLAGS: -Wno-incompatible-pointer-types
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: python -m pip install --editable ".[dev]"

      - name: Generate Documentation in HTML format
        run: PYTHONPATH="$PYTHONPATH:$(pwd)" make cython doc

      - uses: actions/upload-pages-artifact@v5
        with: { path: 'doc/build/html' }

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      pages: write
      id-token: write
    environment: { name: 'docs', url: '${{ steps.deployment.outputs.page_url }}' }
    steps: [ { id: 'deployment', uses: 'actions/deploy-pages@v5' } ]
